package model

// Generated by https://quicktype.io

type QuestionInfo struct {
    Data QuestionInfoData `json:"data"`
}

type QuestionInfoData struct {
    UserProfileUserQuestionProgress UserProfileUserQuestionProgress `json:"userProfileUserQuestionProgress"`
}

type UserProfileUserQuestionProgress struct {
    NumAcceptedQuestions  []NumEdQuestion `json:"numAcceptedQuestions"` 
    NumFailedQuestions    []NumEdQuestion `json:"numFailedQuestions"`   
    NumUntouchedQuestions []NumEdQuestion `json:"numUntouchedQuestions"`
    Typename              string          `json:"__typename"`           
}

type NumEdQuestion struct {
    Difficulty string `json:"difficulty"`
    Count      int64  `json:"count"`     
    Typename   string `json:"__typename"`
}
